---
client:
  hosts:
    - ${ELASTICSEARCH_SERVICE}
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile: /var/log/elasticsearch-curator.log
  logformat: logstash
  blacklist: ['elasticsearch', 'urllib3']

