apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: filebeat-images
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    generation: 1
    labels:
      build: filebeat-builder
    name: filebeat-builder
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/efk/filebeat-builder:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      build: filebeat
    name: filebeat
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/efk/filebeat:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: filebeat-builder
    name: filebeat-builder
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: filebeat-builder:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: filebeat/builder
      git:
        uri: https://gitblit.infonova.at/r/~bhois/openshift.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: base-centos7:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: CRkISgjUYc68TgHhtlWc
      type: GitHub
    - generic:
        secret: QCsAJ_PULCsr7F0kHQ2K
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      build: filebeat
    name: filebeat
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: filebeat:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: filebeat/application-test
      git:
        uri: https://gitblit.infonova.at/r/~bhois/openshift.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: filebeat-builder:latest
          namespace: efk
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: F6Oz0WtZ4el5x6s28dRW
      type: GitHub
    - generic:
        secret: tgSWW06CVMnD67TnXlpJ
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
