apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
    - name: tomcat
      image: gencatcloud/tomcat-openshift:8
      volumeMounts:
        - name: applog
          mountPath: /opt/tomcat/logs
    - name: filebeat
      image: docker-registry.default.svc:5000/efk/filebeat
      env:
        - name: COMPONENT
          value: tomcat
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      volumeMounts:
        - name: applog
          mountPath: /opt/tomcat/logs
  volumes:
    - name: applog
      emptyDir: {}
