apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: riemann
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: riemann
    name: riemann
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/efk/riemann:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    generation: 1
    labels:
      build: riemann-builder
    name: riemann-builder
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/efk/riemann-builder:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: riemann
    name: riemann
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: riemann:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: riemann/application-test
      git:
        uri: https://gitblit.infonova.at/r/~bhois/openshift.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: riemann-builder:latest
          namespace: efk
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: XcXyoJ8OEWgPCMbNOG5H
      type: GitHub
    - generic:
        secret: 9rwoZ7v_yPNPs4B9imp5
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: riemann-builder
    name: riemann-builder
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: riemann-builder:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: riemann/builder
      git:
        uri: https://bhois@gitblit.infonova.at/r/~bhois/openshift.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: base-centos7:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: zdp3wcOi4dHPAkdRy5rN
      type: GitHub
    - generic:
        secret: 6VEcm3yli1OmNxqNngbj
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: riemann
    name: riemann
  spec:
    replicas: 1
    selector:
      app: riemann
      deploymentconfig: riemann
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: riemann
          deploymentconfig: riemann
      spec:
        containers:
        - image: docker-registry.default.svc:5000/efk/riemann@sha256:06cba42b72aea5a7e4d0ac3d2569260a2bf0ee20ebd83d29c3613e13c98c591b
          imagePullPolicy: Always
          name: riemann
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - riemann
        from:
          kind: ImageStreamTag
          name: riemann:latest
          namespace: efk
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: riemann
    name: riemann
  spec:
    selector:
      app: riemann
    ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
